Repository softeerbootcamp-6th/Team3-SockThree, pull requests merged in 2025-08, with the labels that each got.

#72 버튼 컴포넌트 구현
  client/global.css
  client/src/App.tsx
  client/src/assets/icons/default/colored-heart.svg
  client/src/assets/icons/default/heart.svg
  client/src/assets/icons/gradient/edit.svg
  client/src/shared/component/Button.tsx
  client/src/shared/component/CircleButton.tsx
Labels: design, frontend

#89 [FEATURE] - 강좌 도메인 생성
  server/src/main/java/com/seniclass/server/domain/lecture/domain/Lecture.java
  server/src/main/java/com/seniclass/server/domain/lecture/enums/Level.java
  server/src/main/java/com/seniclass/server/domain/lecture/repository/LectureRepository.java
Labels: backend, feature

#78 Progress bar 컴포넌트 퍼블리싱
  client/src/shared/components/ProgressBar.tsx
Labels: design, frontend

#86 임박 강좌 정원 확인 카드 퍼블리싱
  client/global.css
  client/package-lock.json
  client/package.json
  client/src/assets/icons/default/person.svg
  client/src/assets/icons/tooltip/tooltip-round.svg
  client/src/shared/components/Chips.tsx
  client/src/shared/components/ProgressBar.tsx
  client/src/shared/components/RoundTooltip.tsx
  client/src/user/student/component/HoverExpandCourseCard.tsx
  client/src/user/student/page/StudentHomePage.tsx
  client/src/user/student/view/HoverExpandCourseCardView.tsx
Labels: design, frontend

#211 [FEATURE] - 시니어 사용자 마이페이지 카드 수정
  client/src/domain/student/component/mypage/MyPageCard.tsx
  client/src/domain/student/page/mypage/MyPage.tsx
Labels: frontend

#243 [FEATURE] - 수강 중 강좌 페이지 퍼블리싱
  client/src/domain/student/component/course/CourseProgressCard.tsx
  client/src/domain/student/page/index.tsx
  client/src/domain/student/page/mypage/CurrentCoursePage.tsx
  client/src/domain/student/page/mypage/MyCoursePage.tsx
  client/src/routes/index.tsx
  client/src/shared/components/InfoChip.tsx
Labels: frontend

#269 [FEATURE] - FE 인증/인가 처리
  client/src/routes/RouteByRole.tsx
  client/src/routes/index.tsx
  client/src/routes/instructorRouter.ts
  client/src/routes/studentRouter.ts
  client/src/shared/api/refresh.ts
  client/src/shared/auth/checkAuth.ts
  client/src/shared/context/AuthContext.tsx
  client/src/shared/hook/useAuth.tsx
  client/src/shared/layout/RootLayout.tsx
  client/src/shared/page/error/Error404.tsx
  client/src/shared/types/auth.ts
Labels: frontend
